# (Optional) Global filters, will be applied in order
filters:
  - ForwardFormatFilter: # Filter name under telemirror/messagefilters.py
      # Filters arguments
      format: "{message_text}\n\nForwarded from [{channel_name}]({message_link})"
  - EmptyMessageFilter
  - UrlMessageFilter:
      blacklist: !!set
        ? t.me
  - SkipUrlFilter:
      skip_mention: false

# (Optional) Global settings
disable_edit: true
disable_delete: true

# (Required) Mirror directions
directions:
  - from: [-1001589399161]
    to: [-1001836455250, -1001867762925, -1001852796609]

  - from: [-1001871766752]
    to: [-1001562195772, -1001347977016, -1001733199020, -1001832085294, -1001849017994, -1001928370532, -1001890039607, -1001816164988]

  - from: [-1001797626445]
    to: [-1001822541447]
    # Overwrite global settings
    disable_edit: false
    disable_delete: false
    # Overwrite global filters
    filters:
      - UrlMessageFilter:
          blacklist: !!set
            ? t.me
